### ISSUE TITLE
Exam 21 - Question 11 ?

### ISSUE THREAD

**Issue by StefH** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#187]
A company wants to use Amazon Elastic Compute Cloud (Amazon EC2) to deploy a global commercial application. The deployment solution should be built with the highest redundancy and fault tolerance.
Based on this situation, the Amazon EC2 instances should be deployed:

A. in a single Availability Zone in one AWS Region
B. with multiple Elastic Network Interfaces belonging to different subnets
C. across multiple Availability Zones in one AWS Region
D. across multiple Availability Zones in two AWS Regions

The answer given is C, but shouldn't this be D?

**Comment by mametur** [comment]
@StefH Deploying across multiple AWS Regions also provides redundancy, but it introduces additional complexities such as data replication, higher latency due to cross-region communication, and potentially higher costs. While deploying across multiple regions can be suitable for certain disaster recovery scenarios or to serve geographically dispersed users, it may not be necessary for all applications and can add unnecessary complexity.

**Comment by kananinirav** [comment]
@mametur 💯 ✅  @StefH Correct answer is C
