### ISSUE TITLE
Practice Test 4 Question 27

### ISSUE THREAD

**Issue by ProttoySarker** [kananinirav/AWS-Certified-Cloud-Practitioner-Notes#246]
Hello!

The answer choice that is presented is correct for Practice Test #4, Question #27 is incorrect. The correct answer on the exam is "Controls that the customer and AWS collaborate together upon to secure the infrastructure", however, the correct answer should be "Controls that apply to both the infrastructure layer and customer layers." 

Please fix this issue.

**Comment by kananinirav** [comment]
@ProttoySarker 

According to my understanding 

C. Controls that apply to both the infrastructure layer and customer layers is incorrect because it doesn't accurately describe the nature of shared controls in the AWS shared responsibility model.

Why D is the better answer compared to C 

Shared controls in AWS are specifically about collaboration between AWS and the customer. AWS handles the security of the cloud infrastructure, while customers are responsible for securing their data and applications within the cloud.

C suggests that controls apply to both infrastructure and customer layers, but it doesn't address the collaborative nature of these controls or the specific responsibilities of AWS and the customer. The key aspect of shared controls is that they are jointly managed, with AWS providing the base infrastructure and the customer configuring and maintaining security at the application level.
